/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://beta.skaffolder.com/#!/register?friend=5ce1adcf63897a72058db532
*
* You will get 10% discount for each one of your friends
* 
*/
// Import Libraries
import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
// Import Services
import { CouponService } from '../../services/coupon.service';
import { OrderService } from '../../services/order.service';
import { UserService } from '../../services/user.service';
// Import Models
import { Coupon } from '../../domain/estore_db/coupon';
import { Order } from '../../domain/estore_db/order';
import { User } from '../../domain/estore_db/user';

// START - USED SERVICES
/**
* CouponService.create
*	@description CRUD ACTION create
*
* OrderService.findBy_coupon
*	@description CRUD ACTION findBy_coupon
*	@param Objectid key Id della risorsa _coupon da cercare
*
* CouponService.get
*	@description CRUD ACTION get
*	@param ObjectId id Id 
*
* UserService.list
*	@description CRUD ACTION list
*
* CouponService.update
*	@description CRUD ACTION update
*	@param ObjectId id Id
*
*/
// END - USED SERVICES

/**
 * This component allows to edit a Coupon
 */
@Component({
    selector: 'app-coupon-edit',
    templateUrl: 'coupon-edit.component.html',
    styleUrls: ['coupon-edit.component.css']
})
export class CouponEditComponent implements OnInit {
    item: Coupon;
    list_coupon: Coupon[];
    list_users: User[];
    externalOrder: Order[];
    model: Coupon;
    formValid: Boolean;

    constructor(
    private couponService: CouponService,
    private orderService: OrderService,
    private userService: UserService,
    private route: ActivatedRoute,
    private location: Location) {
        // Init item
        this.item = new Coupon();
        this.externalOrder = [];
    }

    /**
     * Init
     */
    ngOnInit() {
        this.route.params.subscribe(param => {
            const id: string = param['id'];
            if (id !== 'new') {
                this.couponService.get(id).subscribe(item => this.item = item);
                this.orderService.findBy_coupon(id).subscribe(list => this.externalOrder = list);
            }
            // Get relations
            this.userService.list().subscribe(list => this.list_users = list);
        });
    }

    /**
     * Check if an User is in  _users
     *
     * @param {string} id Id of User to search
     * @returns {boolean} True if it is found
     */
    containUser(id: string): boolean {
        if (!this.item._users) return false;
        return this.item._users.indexOf(id) !== -1;
    }

    /**
     * Add User from Coupon
     *
     * @param {string} id Id of User to add in this.item._users array
     */
    addUser(id: string) {
        if (!this.item._users)
            this.item._users = [];
        this.item._users.push(id);
    }

    /**
     * Remove an User from a Coupon
     *
     * @param {number} index Index of User in this.item._users array
     */
    removeUser(index: number) {
        this.item._users.splice(index, 1);
    }

    /**
     * Save Coupon
     *
     * @param {boolean} formValid Form validity check
     * @param Coupon item Coupon to save
     */
    save(formValid: boolean, item: Coupon): void {
        this.formValid = formValid;
        if (formValid) {
            if (item._id) {
                this.couponService.update(item).subscribe(data => this.goBack());
            } else {
                this.couponService.create(item).subscribe(data => this.goBack());
            } 
        }
    }

    /**
     * Go Back
     */
    goBack(): void {
        this.location.back();
    }


}



