/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://beta.skaffolder.com/#!/register?friend=5ce1adcf63897a72058db532
*
* You will get 10% discount for each one of your friends
* 
*/
// Import Libraries
import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
// Import Services
import { CategoryService } from '../../services/category.service';
import { ProductService } from '../../services/product.service';
// Import Models
import { Category } from '../../domain/estore_db/category';
import { Product } from '../../domain/estore_db/product';

// START - USED SERVICES
/**
* CategoryService.create
*	@description CRUD ACTION create
*
* ProductService.findBycategory
*	@description CRUD ACTION findBycategory
*	@param Objectid key Id della risorsa category da cercare
*
* CategoryService.get
*	@description CRUD ACTION get
*	@param ObjectId id Id 
*
* CategoryService.update
*	@description CRUD ACTION update
*	@param ObjectId id Id
*
*/
// END - USED SERVICES

/**
 * This component allows to edit a Category
 */
@Component({
    selector: 'app-category-edit',
    templateUrl: 'category-edit.component.html',
    styleUrls: ['category-edit.component.css']
})
export class CategoryEditComponent implements OnInit {
    item: Category;
    listCategory: Category[];
    externalProduct: Product[];
    model: Category;
    formValid: Boolean;

    constructor(
    private categoryService: CategoryService,
    private productService: ProductService,
    private route: ActivatedRoute,
    private location: Location) {
        // Init item
        this.item = new Category();
        this.externalProduct = [];
    }

    /**
     * Init
     */
    ngOnInit() {
        this.route.params.subscribe(param => {
            const id: string = param['id'];
            if (id !== 'new') {
                this.categoryService.get(id).subscribe(item => this.item = item);
                this.productService.findByCategory(id).subscribe(list => this.externalProduct = list);
            }
            // Get relations
        });
    }


    /**
     * Save Category
     *
     * @param {boolean} formValid Form validity check
     * @param Category item Category to save
     */
    save(formValid: boolean, item: Category): void {
        this.formValid = formValid;
        if (formValid) {
            if (item._id) {
                this.categoryService.update(item).subscribe(data => this.goBack());
            } else {
                this.categoryService.create(item).subscribe(data => this.goBack());
            } 
        }
    }

    /**
     * Go Back
     */
    goBack(): void {
        this.location.back();
    }


}



