/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://beta.skaffolder.com/#!/register?friend=5ce1adcf63897a72058db532
*
* You will get 10% discount for each one of your friends
* 
*/
// DEPENDENCIES
import { NgModule } from '@angular/core';
import { CanActivate, RouterModule, Routes } from '@angular/router';

/* START MY VIEWS IMPORT */
// Do not edit this comment content, it will be overwritten in next Skaffolder generation
import { HomeComponent} from './pages/home/home.component';
import { AdminComponent} from './pages/admin/admin.component';
import { CategoryEditComponent} from './pages/category-edit/category-edit.component';
import { CategoryListComponent} from './pages/category-list/category-list.component';
import { CouponEditComponent} from './pages/coupon-edit/coupon-edit.component';
import { CouponListComponent} from './pages/coupon-list/coupon-list.component';
import { OrderEditComponent} from './pages/order-edit/order-edit.component';
import { OrderListComponent} from './pages/order-list/order-list.component';
import { ProductEditComponent} from './pages/product-edit/product-edit.component';
import { ProductListComponent} from './pages/product-list/product-list.component';

/* END MY VIEWS IMPORT */

// SECURITY
import { LoginComponent } from './pages/login/login.component';
import { ManageUserEditComponent } from './security/manage-user/edit-user/manage-user-edit.component';
import { ManageUserListComponent } from './security/manage-user/list-user/manage-user-list.component';
import { ProfileComponent } from './security/profile/profile.component';
import { AuthGuard } from './security/auth.guard';

/**
 * WEB APP ROUTES
 */
const routes: Routes = [
    { path: '', redirectTo: '/home', pathMatch: 'full'  },

    /* START MY VIEWS */

    { path: 'admin',  loadChildren: './pages/admin/admin.module#AdminModule' , canActivate: [AuthGuard] },
    { path: 'categorys/:id',  loadChildren: './pages/category-edit/category-edit.module#CategoryEditModule' , canActivate: [AuthGuard] },
    { path: 'categorys',  loadChildren: './pages/category-list/category-list.module#CategoryListModule' , canActivate: [AuthGuard] },
    { path: 'coupons/:id',  loadChildren: './pages/coupon-edit/coupon-edit.module#CouponEditModule' , canActivate: [AuthGuard] },
    { path: 'coupons',  loadChildren: './pages/coupon-list/coupon-list.module#CouponListModule' , canActivate: [AuthGuard] },
    { path: 'home',  loadChildren: './pages/home/home.module#HomeModule'  },
    { path: 'orders/:id',  loadChildren: './pages/order-edit/order-edit.module#OrderEditModule' , canActivate: [AuthGuard] },
    { path: 'orders',  loadChildren: './pages/order-list/order-list.module#OrderListModule' , canActivate: [AuthGuard] },
    { path: 'products/:id',  loadChildren: './pages/product-edit/product-edit.module#ProductEditModule' , canActivate: [AuthGuard] },
    { path: 'shop/:id',  loadChildren: './pages/product-edit/product-edit.module#ProductEditModule'  },
    { path: 'products',  loadChildren: './pages/product-list/product-list.module#ProductListModule' , canActivate: [AuthGuard] },

 /* END MY VIEWS */

    // SECURITY
    { path: 'manage-users',  loadChildren: './security/manage-user/list-user/manage-user-list.module#ManageUserListModule', canActivate: [AuthGuard], data: ['ADMIN']},
    { path: 'manage-users/:id',  loadChildren: './security/manage-user/edit-user/manage-user-edit.module#ManageUserEditModule', canActivate: [AuthGuard], data: ['ADMIN']},
    { path: 'profile',  loadChildren: './security/profile/profile.module#ProfileModule', canActivate: [AuthGuard] },
    { path: 'login', loadChildren: './pages/login/login.module#LoginModule'}
];

/**
 * ROUTING MODULE
 */
@NgModule({
    imports: [ RouterModule.forRoot(routes) ],
    exports: [ RouterModule ]
})

export class AppRoutingModule {}
