/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://beta.skaffolder.com/#!/register?friend=5ce1adcf63897a72058db532
*
* You will get 10% discount for each one of your friends
* 
*/
import { Component } from '@angular/core';
import { OnInit } from '@angular/core';
// Import Services
import { ProductService } from '../../services/product.service';
// Import Models
import { Product } from '../../domain/estore_db/product';

// START - USED SERVICES
/**
* ProductService.delete
*	@description CRUD ACTION delete
*	@param ObjectId id Id
*
* ProductService.list
*	@description CRUD ACTION list
*
*/
// END - USED SERVICES

/**
 * This component shows a list of Product
 * @class ProductListComponent
 */
@Component({
    selector: 'app-product-list',
    templateUrl: './product-list.component.html',
    styleUrls: ['./product-list.component.css']
})
export class ProductListComponent implements OnInit {
    list: Product[];
    search: any = {};
    idSelected: string;
    constructor(
        private productService: ProductService,
    ) { }

    /**
     * Init
     */
    ngOnInit(): void {
        this.productService.list().subscribe(list => this.list = list);
    }

    /**
     * Select Product to remove
     *
     * @param {string} id Id of the Product to remove
     */
    selectId(id: string) {
        this.idSelected = id;
    }

    /**
     * Remove selected Product
     */
    deleteItem() {
        this.productService.remove(this.idSelected).subscribe(data => this.list = this.list.filter(el => el._id !== this.idSelected));
    }

}
