/*
 * Generated by
 *
 *      _____ _          __  __      _     _
 *     / ____| |        / _|/ _|    | |   | |
 *    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
 *     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
 *     ____) |   < (_| | | | || (_) | | (_| |  __/ |
 *    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
 *
 * The code generator that works in many programming languages
 *
 *			https://www.skaffolder.com
 *
 *
 * You can generate the code from the command-line
 *       https://npmjs.com/package/skaffolder-cli
 *
 *       npm install -g skaffodler-cli
 *
 *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
 *
 * To remove this comment please upgrade your plan here:
 *      https://app.skaffolder.com/#!/upgrade
 *
 * Or get up to 70% discount sharing your unique link:
 *       https://beta.skaffolder.com/#!/register?friend=5ce1adcf63897a72058db532
 *
 * You will get 10% discount for each one of your friends
 *
 */
// Import Libraries
import { Component } from '@angular/core';
import { Location } from '@angular/common';

// Import Services
import { ProductService } from '../../services/product.service';
import { CategoryService } from '../../services/category.service';

// Import Models
import { Product } from '../../domain/estore_db/product';

// START - USED SERVICES
/**
 * ProductService.list
 *	@description CRUD ACTION list
 *
 * CategoryService.list
 *	@description CRUD ACTION list
 *
 */
// END - USED SERVICES

/**
 * Home Component
 */
@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent {
  list: Product[];

  constructor(
    private productService: ProductService,
    private categoryService: CategoryService,
    private location: Location
  ) {}

  /**
   * Init
   */
  ngOnInit(): void {
    this.productService.list().subscribe(list => (this.list = list));
  }

  /**
   * Buy
   */
  buy(): void {
    alert('Next time I will be faster :-)');
  }
}
