/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://beta.skaffolder.com/#!/register?friend=5ce1adcf63897a72058db532
*
* You will get 10% discount for each one of your friends
* 
*/
/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE orderBaseService PLEASE EDIT ../order.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Order } from '../../domain/estore_db/order';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Order.service.ts
 */

/*
 * SCHEMA DB Order
 *
	{
		date: {
			type: 'Date'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		_coupon: {
			type: Schema.ObjectId,
			ref : "Order"
		},
		_products: [{
			type: Schema.ObjectId,
			ref : "Order"
		}],
		_user: {
			type: Schema.ObjectId,
			ref : "Order"
		},
	}
 *
 */
@Injectable()
export class OrderBaseService {

    contextUrl: string = environment.endpoint + '/cart';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * OrderService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Order): Observable<Order> {
        return this.http
            .post<Order>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * OrderService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * OrderService.findBy_coupon
    *   @description CRUD ACTION findBy_coupon
    *   @param Objectid key Id della risorsa _coupon da cercare
    *
    */
    findBy_coupon(id: string): Observable<Order[]> {
        return this.http
            .get<Order[]>(this.contextUrl + '/findBy_coupon/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * OrderService.findBy_products
    *   @description CRUD ACTION findBy_products
    *   @param Objectid key Id della risorsa _products da cercare
    *
    */
    findBy_products(id: string): Observable<Order[]> {
        return this.http
            .get<Order[]>(this.contextUrl + '/findBy_products/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * OrderService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id 
    *
    */
    get(id: string): Observable<Order> {
        return this.http
            .get<Order>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * OrderService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Order[]> {
        return this.http
            .get<Order[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * OrderService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Order): Observable<Order> {
        return this.http
            .post<Order>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
